services:
  postgres-db:
    image: postgres:16-alpine
    container_name: pedidos-postgres
    environment:
      POSTGRES_DB: pedidos_db
      POSTGRES_USER: pedidos_user
      POSTGRES_PASSWORD: pedidos_password
    ports:
      - "5434:5432" # 5432 lo ocupa productos-service, 5433 carrito-service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pedidos_user -d pedidos_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
